# Generated by Django 5.2 on 2025-04-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userflag'),
        ('users', '0004_add_hackathon_achievements'),
    ]

    operations = [
    ]
