# Generated by Django 5.2 on 2025-04-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_quotesubmission_user'),
        ('challenges', 'add_correctness_level'),
    ]

    operations = [
    ]
