# Generated by Django 5.2 on 2025-04-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_add_correctness_level'),
        ('challenges', '0002_alter_quotesubmission_user'),
    ]

    operations = [
    ]
