# Generated by Django 5.2 on 2025-04-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_merge_20250424_1840'),
        ('challenges', 'fix_correctness_level'),
    ]

    operations = [
    ]
