# Generated by Django 5.2 on 2025-04-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_merge_0003_merge_20250424_1840_fix_correctness_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesolution',
            name='correctness_level',
            field=models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partially Correct'), ('incorrect', 'Incorrect')], default='correct', max_length=20),
        ),
    ]
