# Generated by Django 5.2 on 2025-04-21 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywin',
            name='celebrations',
            field=models.ManyToManyField(blank=True, related_name='celebrated_wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
